spring.application.name=bloque4_axity
# Indicar a Spring Boot que busque nuestro archivo de configuración de base de datos en formato XML
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Habilitar la consola web de H2 para que podamos ver la base de datos más adelante
spring.h2.console.enabled=true